### ISSUE TITLE
[Feature Request] Adding Robert Broglia's Pre-Release Builds

### ISSUE THREAD

**Issue by privateemu** [RJNY/Obtainium-Emulation-Pack#5]
Another set of emulators that would be great to add would be Robert Broglia's emulators. These ones are on GitHub, however I'm not sure how one would keep track of knowing when to update given that it seems the same pre-release release is used over and over: https://github.com/Rakashazi/emu-ex-plus-alpha/releases/

**Comment by RJNY** [comment]
I've never seen these before. Are these just stand-alone emulators for android? Why use these over RetroArch?

I have a few thoughts on this:

1. As you've already stated, This is really difficult to track given they reuse the same `pre-release` tag again and again. There's no indicators to automate on.
2. This repo works as a bundle, so there's no telling what updated and what didn't. If it was implemented, it'd most likely be an all-or-nothing.
3. That's a lot of links! you're gonna spam your obtainium with a bunch of emulators, nightly!
4. Assuming we can get it working, the "Obtainium Emulation Pack" aims to be *lightweight* and contain *essentials* of all things to get started on a new device as quickly as possible.  I wonder if this has a better home on the obtainiums crowdsourced front-end site since this feels like a niche request?

**Comment by privateemu** [comment]
The Broglia emulators are the .emu series, here's a link to them [on the Play Store](https://play.google.com/store/apps/developer?id=Robert+Broglia&hl=en_US). I personally prefer stand alone emulators to RetroArch, but yes in theory RetroArch covers these.

I think your point 3/4 are the biggest ones to not add them, it's quite fair that adding this number would really explode the emulation pack in size, unless one could like select which ones they wanted easily, which to your point, going to the crowdsourced front end would be easier.

And then 1/2 make the actual implementation difficult. I might explore these independently to see if I can figure out a way to get them. I think to a degree Broglia doesn't want it to be too easy as these dev builds remove the need to buy his emulators on the Play Store.
